import type {
  CareCase,
  CellMeeting,
  PastoralAlert,
  PastoralCell,
  PastoralMinistry,
  PastoralPerson,
  PermissionPreset,
  PersonRelationship,
  PersonTag,
  PrayerRequest,
  TimelineEvent,
} from "./types";

export const pastoralTags: PersonTag[] = [
  { id: "novo-convertido", label: "Novo convertido", color: "brand" },
  { id: "em-acompanhamento", label: "Em acompanhamento", color: "amber" },
  { id: "lideranca", label: "Lideranca", color: "info" },
  { id: "louvor", label: "Louvor", color: "success" },
  { id: "kids", label: "Kids", color: "brand" },
  { id: "casais", label: "Casais", color: "danger" },
  { id: "jovens", label: "Jovens", color: "info" },
  { id: "visitante", label: "Visitante", color: "neutral" },
  { id: "consolidado", label: "Consolidado", color: "success" },
];

export const pastoralMinistries: PastoralMinistry[] = [
  { id: "louvor", name: "Louvor", icon: "music", color: "#5A8F6E" },
  { id: "kids", name: "SkyKids", icon: "baby", color: "#F4532A" },
  { id: "boas-vindas", name: "Boas Vindas", icon: "heart", color: "#C49A3C" },
  { id: "midia", name: "Midia", icon: "camera", color: "#5B7FA6" },
  { id: "producao", name: "Producao", icon: "church", color: "#D94420" },
];

export const pastoralPeople: PastoralPerson[] = [
  {
    id: "ana-souza",
    fullName: "Ana Souza",
    avatarColor: "#F4532A",
    photoUrl: "https://i.pravatar.cc/150?img=5",
    phone: "(85) 99981-2210",
    email: "ana.souza@servos.local",
    birthDate: "1996-03-12",
    gender: "feminino",
    maritalStatus: "casado",
    address: "Rua das Flores, 120",
    instagram: "@anasouza",
    arrivalDate: "2025-11-16",
    kinds: ["member", "volunteer"],
    baptized: true,
    inDiscipleship: false,
    participatesInCell: true,
    cellId: "jardim",
    ministryIds: ["louvor", "boas-vindas"],
    roleTitle: "Vocal e acolhimento",
    tagIds: ["louvor", "casais", "em-acompanhamento"],
    notes: "Tem buscado retomar constancia na celula depois de semanas intensas no trabalho.",
    lastContactAt: "2026-05-20",
  },
  {
    id: "bruno-lima",
    fullName: "Bruno Lima",
    avatarColor: "#5B7FA6",
    photoUrl: "https://i.pravatar.cc/150?img=12",
    phone: "(85) 98844-1002",
    email: "bruno.lima@servos.local",
    birthDate: "2002-07-04",
    gender: "masculino",
    maritalStatus: "solteiro",
    address: "Av. Central, 900",
    instagram: "@brunolima",
    arrivalDate: "2026-04-07",
    kinds: ["visitor", "disciple"],
    baptized: false,
    inDiscipleship: true,
    participatesInCell: true,
    cellId: "jovens-norte",
    ministryIds: [],
    roleTitle: "Novo na comunidade",
    tagIds: ["novo-convertido", "jovens", "visitante"],
    notes: "Primeiros passos na fe. Participou de tres encontros seguidos.",
    lastContactAt: "2026-05-24",
  },
  {
    id: "carla-mendes",
    fullName: "Carla Mendes",
    avatarColor: "#C49A3C",
    photoUrl: "https://i.pravatar.cc/150?img=47",
    phone: "(85) 98733-4421",
    email: "carla.mendes@servos.local",
    birthDate: "1988-09-18",
    gender: "feminino",
    maritalStatus: "casado",
    address: "Condominio Vida, casa 18",
    instagram: "@carlamendes",
    arrivalDate: "2021-02-03",
    kinds: ["leader", "volunteer", "member"],
    baptized: true,
    inDiscipleship: true,
    participatesInCell: true,
    cellId: "jardim",
    ministryIds: ["kids"],
    roleTitle: "Lider de celula",
    tagIds: ["lideranca", "kids", "consolidado"],
    notes: "Lidera com cuidado e costuma perceber necessidades cedo.",
    lastContactAt: "2026-05-25",
  },
  {
    id: "diego-rocha",
    fullName: "Diego Rocha",
    avatarColor: "#5A8F6E",
    photoUrl: "https://i.pravatar.cc/150?img=57",
    phone: "(85) 98122-7620",
    email: "diego.rocha@servos.local",
    birthDate: "1991-01-27",
    gender: "masculino",
    maritalStatus: "casado",
    address: "Rua Azul, 44",
    instagram: "@diegorocha",
    arrivalDate: "2019-08-11",
    kinds: ["pastor", "leader"],
    baptized: true,
    inDiscipleship: true,
    participatesInCell: false,
    cellId: null,
    ministryIds: ["producao"],
    roleTitle: "Pastor de cuidado",
    tagIds: ["lideranca", "consolidado"],
    notes: "Acompanha lideres de celula e casos pastorais sensiveis.",
    lastContactAt: "2026-05-26",
  },
  {
    id: "elisa-nunes",
    fullName: "Elisa Nunes",
    avatarColor: "#B85C50",
    photoUrl: "https://i.pravatar.cc/150?img=9",
    phone: "(85) 98661-3901",
    email: "elisa.nunes@servos.local",
    birthDate: "1999-12-05",
    gender: "feminino",
    maritalStatus: "solteiro",
    address: "Rua das Mangueiras, 78",
    instagram: "@elisanunes",
    arrivalDate: "2026-03-02",
    kinds: ["visitor"],
    baptized: false,
    inDiscipleship: false,
    participatesInCell: false,
    cellId: null,
    ministryIds: [],
    roleTitle: "Visitante recorrente",
    tagIds: ["visitante", "em-acompanhamento"],
    notes: "Visitou cultos recentes, ainda sem celula.",
    lastContactAt: null,
  },
  {
    id: "felipe-araujo",
    fullName: "Felipe Araujo",
    avatarColor: "#333333",
    photoUrl: "https://i.pravatar.cc/150?img=68",
    phone: "(85) 98400-1122",
    email: "felipe.araujo@servos.local",
    birthDate: "1994-05-30",
    gender: "masculino",
    maritalStatus: "casado",
    address: "Rua Nova, 232",
    instagram: "@felipearaujo",
    arrivalDate: "2020-10-19",
    kinds: ["leader", "volunteer", "member"],
    baptized: true,
    inDiscipleship: true,
    participatesInCell: true,
    cellId: "jovens-norte",
    ministryIds: ["midia", "producao"],
    roleTitle: "Lider de departamento",
    tagIds: ["lideranca", "jovens", "consolidado"],
    notes: "Tem acumulado muitas escalas nos ultimos fins de semana.",
    lastContactAt: "2026-05-22",
  },
];

export const pastoralCells: PastoralCell[] = [
  {
    id: "jardim",
    name: "Celula Jardim",
    coverColor: "#FFF0EC",
    description: "Familias e casais se reunindo para comunhao, palavra e cuidado mutuo.",
    leaderId: "carla-mendes",
    coLeaderId: "ana-souza",
    supervisorId: "diego-rocha",
    address: "Rua das Flores, 120",
    weekDay: "Quarta",
    time: "20:00",
    maxMembers: 14,
    audience: "Casais e familias",
    status: "active",
    members: [
      { personId: "carla-mendes", status: "active", joinedAt: "2024-02-10" },
      { personId: "ana-souza", status: "care", joinedAt: "2025-11-20" },
    ],
    health: { frequency: 76, communion: 88, participation: 70, growth: 58, engagement: 74, care: 82 },
  },
  {
    id: "jovens-norte",
    name: "Jovens Norte",
    coverColor: "#EBF1F7",
    description: "Encontro de jovens com foco em discipulado, amizade e primeiros passos.",
    leaderId: "felipe-araujo",
    coLeaderId: null,
    supervisorId: "diego-rocha",
    address: "Av. Central, 900",
    weekDay: "Sexta",
    time: "19:30",
    maxMembers: 18,
    audience: "Jovens",
    status: "active",
    members: [
      { personId: "felipe-araujo", status: "active", joinedAt: "2024-08-01" },
      { personId: "bruno-lima", status: "visitor", joinedAt: "2026-04-18" },
    ],
    health: { frequency: 84, communion: 78, participation: 81, growth: 72, engagement: 77, care: 66 },
  },
];

export const cellMeetings: CellMeeting[] = [
  {
    id: "meeting-jardim-1",
    cellId: "jardim",
    date: "2026-05-20",
    time: "20:00",
    theme: "Permanecer em Cristo",
    word: "Joao 15",
    notes: "Conversa honesta sobre rotina, familia e constancia.",
    feeling: "boa",
    spiritualEnvironment: ["comunhao", "conexao"],
    needs: ["pessoas precisando cuidado", "pedidos oracao"],
    feedback: "A reuniao foi tranquila e abriu espaco para Ana compartilhar uma fase sensivel.",
    attendance: [
      { personId: "carla-mendes", status: "present" },
      { personId: "ana-souza", status: "present" },
    ],
  },
  {
    id: "meeting-jovens-1",
    cellId: "jovens-norte",
    date: "2026-05-23",
    time: "19:30",
    theme: "Identidade",
    word: "Efesios 1",
    notes: "Bruno trouxe um amigo pela primeira vez.",
    feeling: "muito_boa",
    spiritualEnvironment: ["participacao", "conexao"],
    needs: ["acompanhamento necessario"],
    feedback: "Ambiente leve, muitos jovens participando e abertura para discipulado.",
    attendance: [
      { personId: "felipe-araujo", status: "present" },
      { personId: "bruno-lima", status: "first_visit" },
    ],
  },
];

export const timelineEvents: TimelineEvent[] = [
  {
    id: "tl-1",
    personId: "bruno-lima",
    cellId: "jovens-norte",
    type: "discipleship_started",
    title: "Iniciou discipulado",
    description: "Felipe marcou o primeiro encontro de acompanhamento com Bruno.",
    date: "2026-05-24T18:30:00",
    tone: "brand",
  },
  {
    id: "tl-2",
    personId: "ana-souza",
    cellId: "jardim",
    type: "care_done",
    title: "Acompanhamento realizado",
    description: "Carla conversou com Ana apos a reuniao da celula.",
    date: "2026-05-21T09:20:00",
    tone: "success",
  },
  {
    id: "tl-3",
    personId: "elisa-nunes",
    type: "visit",
    title: "Visitou o culto",
    description: "Terceira presenca em quatro semanas. Ainda sem celula vinculada.",
    date: "2026-05-19T10:00:00",
    tone: "info",
  },
  {
    id: "tl-4",
    personId: "ana-souza",
    cellId: "jardim",
    type: "absence",
    title: "Faltou reuniao da celula",
    description: "Ausencia registrada antes do acompanhamento recente.",
    date: "2026-05-14T20:00:00",
    tone: "amber",
  },
  {
    id: "tl-5",
    personId: "felipe-araujo",
    ministryId: "midia",
    type: "schedule_confirmed",
    title: "Confirmou escala",
    description: "Confirmou participacao na escala de Midia.",
    date: "2026-05-13T12:10:00",
    tone: "success",
  },
];

export const careCases: CareCase[] = [
  {
    id: "care-ana",
    personId: "ana-souza",
    responsibleId: "carla-mendes",
    title: "Retomar constancia na celula",
    reason: "Ausencias recentes e sobrecarga familiar.",
    status: "in_progress",
    priority: "medium",
    openedAt: "2026-05-15",
    nextStep: "Carla vai ligar no sabado para orar e combinar o proximo encontro.",
    notes: ["Ana pediu oracao pela rotina com trabalho e familia.", "Lideranca percebeu abertura para acompanhamento."],
  },
  {
    id: "care-elisa",
    personId: "elisa-nunes",
    responsibleId: "diego-rocha",
    title: "Conectar visitante recorrente",
    reason: "Elisa tem visitado cultos, mas ainda nao entrou em celula.",
    status: "open",
    priority: "high",
    openedAt: "2026-05-19",
    nextStep: "Apresentar Elisa para uma lider de celula no proximo culto.",
    notes: ["Ela demonstrou interesse em participar de um encontro menor."],
  },
];

export const pastoralAlerts: PastoralAlert[] = [
  {
    id: "alert-elisa-cell",
    personId: "elisa-nunes",
    title: "Visitante recorrente sem celula",
    message: "Elisa visitou cultos recentes. Talvez seja um bom momento para apresenta-la a uma celula.",
    severity: "attention",
    createdAt: "2026-05-25",
    actionLabel: "Sugerir celula",
  },
  {
    id: "alert-bruno-discipleship",
    personId: "bruno-lima",
    cellId: "jovens-norte",
    title: "Novo convertido em primeiros passos",
    message: "Bruno iniciou discipulado. Vale acompanhar os proximos retornos com carinho.",
    severity: "gentle",
    createdAt: "2026-05-24",
    actionLabel: "Ver acompanhamento",
  },
  {
    id: "alert-felipe-load",
    personId: "felipe-araujo",
    title: "Lider com muitas responsabilidades",
    message: "Felipe tem liderado celula e acumulado escalas. Pode ser saudavel revisar apoio e descanso.",
    severity: "urgent",
    createdAt: "2026-05-22",
    actionLabel: "Planejar apoio",
  },
];

export const prayerRequests: PrayerRequest[] = [
  {
    id: "prayer-ana",
    personId: "ana-souza",
    title: "Rotina da familia",
    description: "Pedir direcao e descanso para uma fase de trabalho intenso.",
    status: "open",
    createdAt: "2026-05-20",
    private: false,
  },
  {
    id: "prayer-bruno",
    personId: "bruno-lima",
    title: "Primeiros passos na fe",
    description: "Orar por firmeza, entendimento da Palavra e boas amizades.",
    status: "open",
    createdAt: "2026-05-23",
    private: false,
  },
];

export const pastoralRelationships: PersonRelationship[] = [
  { personId: "bruno-lima", relatedPersonId: "felipe-araujo", type: "discipler", label: "Discipulador" },
  { personId: "ana-souza", relatedPersonId: "carla-mendes", type: "cell_leader", label: "Lider de celula" },
  { personId: "carla-mendes", relatedPersonId: "diego-rocha", type: "pastor", label: "Pastor responsavel" },
  { personId: "felipe-araujo", relatedPersonId: "diego-rocha", type: "pastor", label: "Supervisor pastoral" },
];

export const permissionPresets: PermissionPreset[] = [
  {
    id: "admin_geral",
    label: "Admin Geral",
    description: "Acesso total ao Servos, configuracoes e modulos pastorais.",
    access: ["Tudo no sistema", "Configuracoes", "Permissoes", "Relatorios completos"],
  },
  {
    id: "pastor",
    label: "Pastor",
    description: "Visao ampla para cuidado, acompanhamento e dashboards pastorais.",
    access: ["CRM Pastoral", "Dashboard Pastoral", "Acompanhamentos", "Timeline"],
  },
  {
    id: "lider_departamento",
    label: "Lider de Departamento",
    description: "Cuida de voluntarios, escalas e comunicacao do seu departamento.",
    access: ["Membros do departamento", "Escalas", "Comunicacao", "Voluntarios"],
  },
  {
    id: "lider_celula",
    label: "Lider de Celula",
    description: "Acompanha sua propria celula, reunioes, presencas e feedbacks.",
    access: ["Propria celula", "Membros", "Reunioes", "Feedbacks"],
  },
  {
    id: "membro",
    label: "Membro",
    description: "Acompanha perfil pessoal, escalas, pedidos de oracao e confirmacoes.",
    access: ["Perfil pessoal", "Minhas escalas", "Pedidos de oracao", "Confirmacoes"],
  },
];
